export const REQUEST_SAVE_EMAIL = 'REQUEST_SAVE_EMAIL';
export const REQUEST_SAVE_NAME = 'REQUEST_SAVE_NAME';
export const REQUEST_TIME = 'REQUEST_TIME';
export const REQUEST_ADD_SCORE_AND_ASSERTIONS = 'REQUEST_ADD_SCORE_AND_ASSERTIONS';
export const REQUEST_INCREMENT_OF_INDEX_PLAYER = 'REQUEST_INCREMENT_OF_INDEX_PLAYER';
export const REQUEST_RESET_STATE = 'REQUEST_RESET_STATE';
